services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: examples:latest
    ports:
      - '9001:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLARITY_DISABLED=${CLARITY_DISABLED}
